version: "3.7"

services:
  service-a:
    build:
      context: .
      dockerfile: a/Dockerfile
    privileged: true
    ports:
      - "8011:8011"
    restart: always

  service-b:
    build:
      context: .
      dockerfile: b/Dockerfile
    privileged: true
    ports:
      - "8022:8022"
    restart: always

  service-c:
    build:
      context: .
      dockerfile: c/Dockerfile
    privileged: true

  mysql:
    image: mysql:5.7
    ports:
      - "13306:3306"
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: "MYSQL_ADMIN"
      MYSQL_DATABASE: "testdb"
      BITNAMI_DEBUG: "true"
