version: "3.7"

networks:
  back:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16

services:
  service-a:
    build:
      context: .
      dockerfile: a/Dockerfile
    privileged: true
    ports:
      - "8011:8011"
    restart: always
    depends_on:
      - mysql
    networks:
      - back

  service-b:
    build:
      context: .
      dockerfile: b/Dockerfile
    privileged: true
    ports:
      - "8022:8022"
    restart: always
    networks:
      - back

  service-c:
    build:
      context: .
      dockerfile: c/Dockerfile
    privileged: true
    networks:
      - back

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: "MYSQL_ADMIN"
      MYSQL_DATABASE: "testdb"
      BITNAMI_DEBUG: "true"
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - back
