version: 2.1

jobs:
  build:
    docker:
    # - image: circleci/buildpack-deps:jessie
    # - image: circleci/mysql:5.7.21
    #   environment:
    #     MYSQL_DATABASE: testdb
    #     MYSQL_ROOT_PASSWORD: MYSQL_ADMIN
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run: sudo curl -L https://github.com/docker/compose/releases/download/1.25.4/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
      - run: docker-compose -f _docker-compose.yml up -d
      - run: docker-compose -f _docker-compose.yml exec dind docker-comopose up -d
      - run: docker-compose -f _docker-compose.yml exec dind docker-compose logs service-a
      - run: docker-compose -f _docker-compose.yml exec dind docker-compose run service-c
      - run: docker-compose -f _docker-compose.yml exec dind docker-compose logs service-b
      # - run: docker-compose logs service-a
      # - run: docker-compose logs mysql
      # - run: curl http://localhost:8022
      # - run: docker-compose run service-c
      # - run: docker-compose logs service-b

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
