version: 2.1

jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run: sudo curl -L https://github.com/docker/compose/releases/download/1.25.4/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
      - run: docker-compose up -d
      - run: curl http://localhost:8011

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
